language: objective-c
before_install:
 - rvm use system
 - sudo gem install cocoapods -v '1.0.0'

osx_image: xcode7
xcode_workspace: WeatherAlert.xcworkspace
xcode_scheme: WeatherAlert
xcode_sdk: iphonesimulator9.0
